import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  background: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    width: 'auto',
  },
  scrollContainer: {
    flexGrow: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  header: {
    width: '100%',
    alignItems: 'center',
    marginVertical: 20,
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
  },
  appName: {
    fontSize: 36,
    fontFamily: 'Oswald-Bold',
    color: '#fff',
  },
  tagline: {
    fontSize: 16,
    fontFamily: 'Oswald-Regular',
    color: '#FFA500',
    textAlign: 'center',
    margin: 15,
  },
  notificationIcon: {
    position: 'absolute',
    right: 20,
    top: 20,
  },
  card: {
    width: '90%',
    padding: 20,
    backgroundColor: '#555',
    borderRadius: 10,
    marginVertical: 10,
    alignItems: 'center',
  },
  cardTitle: {
    fontSize: 24,
    color: '#FFA500',
    fontFamily: 'Oswald-Bold',
    marginBottom: 10,
  },
  cardContent: {
    fontSize: 18,
    color: '#fff',
    fontFamily: 'Oswald-Regular',
    textAlign: 'center',
  },
  progressContainer: {
    width: '90%',
    padding: 20,
    backgroundColor: '#444',
    borderRadius: 10,
    marginVertical: 10,
    alignItems: 'center',
  },
  progressTitle: {
    fontSize: 24,
    color: '#FFA500',
    fontFamily: 'Oswald-Bold',
    marginBottom: 10,
  },
  progressContent: {
    fontSize: 18,
    color: '#fff',
    fontFamily: 'Oswald-Regular',
    textAlign: 'center',
  },
  habitsContainer: {
    width: '90%',
    padding: 20,
    backgroundColor: '#444',
    borderRadius: 10,
    marginVertical: 10,
    alignItems: 'center',
  },
  sectionTitle: {
    fontSize: 24,
    color: '#FFA500',
    fontFamily: 'Oswald-Bold',
    marginBottom: 10,
  },
  habitItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#555',
  },
  habitText: {
    fontSize: 18,
    fontFamily: 'Oswald-Regular',
    color: '#fff',
  },
  habitTime: {
    fontSize: 16,
    fontFamily: 'Oswald-Regular',
    color: '#ccc',
  },
  addButton: {
    backgroundColor: '#FFA500',
    alignItems: 'center',
    marginTop: 20,
    width: '100%',
  },
  addButtonText: {
    fontSize: 18,
    color: '#fff',
    fontFamily: 'Oswald-Bold',
  },
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#333',
    padding: 20,
  },
  input: {
    width: '100%',
    backgroundColor: '#555',
    borderRadius: 25,
    padding: 10,
    marginVertical: 10,
    color: '#fff',
    fontFamily: 'Oswald-Regular',
  },
  saveButton: {
    backgroundColor: '#FFA500',
    borderRadius: 25,
    padding: 10,
    alignItems: 'center',
    marginTop: 20,
    width: '100%',
  },
  saveButtonText: {
    fontSize: 18,
    color: '#fff',
    fontFamily: 'Oswald-Bold',
  },
  modalContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  modalContent: {
    width: '80%',
    padding: 20,
    backgroundColor: '#444',
    borderRadius: 10,
    alignItems: 'center',
  },
  modalTitle: {
    fontSize: 24,
    color: '#FFA500',
    fontFamily: 'Oswald-Bold',
    marginBottom: 10,
  },
  modalText: {
    fontSize: 18,
    color: '#fff',
    fontFamily: 'Oswald-Regular',
    textAlign: 'center',
  },
  closeButton: {
    marginTop: 20,
    padding: 10,
    backgroundColor: '#FFA500',
    borderRadius: 25,
    alignItems: 'center',
  },
  closeButtonText: {
    fontSize: 18,
    color: '#fff',
    fontFamily: 'Oswald-Bold',
  },
});

export default styles;